FindaVenue/force-app/main/default/objects/Account/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>City centre</fullName>
            </value>
            <value>
                <fullName>City centre Leeson street</fullName>
            </value>
            <value>
                <fullName>City centre off Grafton street</fullName>
            </value>
            <value>
                <fullName>City centre Harcourt street</fullName>
            </value>
            <value>
                <fullName>City centre Camden street</fullName>
            </value>
            <value>
                <fullName>City centre IFSC</fullName>
            </value>
            <value>
                <fullName>City centre Temple Bar</fullName>
            </value>
            <value>
                <fullName>City centre off O&apos;Connell street</fullName>
            </value>
            <value>
                <fullName>City centre D&apos;olier street</fullName>
            </value>
            <value>
                <fullName>City centre Georges street</fullName>
            </value>
            <value>
                <fullName>City centre Dame street</fullName>
            </value>
            <value>
                <fullName>City centre Merrion row</fullName>
            </value>
            <value>
                <fullName>City centre Dawson street</fullName>
            </value>
            <value>
                <fullName>Dublin 3</fullName>
            </value>
            <value>
                <fullName>Dublin 5</fullName>
            </value>
            <value>
                <fullName>Dublin 7</fullName>
            </value>
            <value>
                <fullName>Dublin 9</fullName>
            </value>
            <value>
                <fullName>Dublin 11</fullName>
            </value>
            <value>
                <fullName>Dublin 13</fullName>
            </value>
            <value>
                <fullName>Dublin 15</fullName>
            </value>
            <value>
                <fullName>Dublin 4</fullName>
            </value>
            <value>
                <fullName>Dublin 6</fullName>
            </value>
            <value>
                <fullName>Dublin 8</fullName>
            </value>
            <value>
                <fullName>Dublin 12</fullName>
            </value>
            <value>
                <fullName>Dublin 14</fullName>
            </value>
            <value>
                <fullName>Dublin 16</fullName>
            </value>
            <value>
                <fullName>Dublin 18</fullName>
            </value>
            <value>
                <fullName>Dublin South county</fullName>
            </value>
            <value>
                <fullName>Dublin North county</fullName>
            </value>
            <value>
                <fullName>Outside Dublin-Leinster</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FindaVenue/force-app/main/default/objects/Account/fields/Banquet_Capacity_double__c.field-meta.xml
<CustomField>
    <fullName>Banquet_Capacity_double__c</fullName>
    <label>Banquet Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

FindaVenue/force-app/main/default/objects/Account/fields/Entire_Venue_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Entire_Venue_Capacity__c</fullName>
    <label>Entire Venue Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

FindaVenue/force-app/main/default/objects/Account/fields/Event_Scenarios__c.field-meta.xml
<CustomField>
    <fullName>Event_Scenarios__c</fullName>
    <label>Event Scenarios</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Summer party</fullName>
            </value>
            <value>
                <fullName>Christmas party</fullName>
            </value>
            <value>
                <fullName>Gala Dinner</fullName>
            </value>
            <value>
                <fullName>Large Reception standing party</fullName>
            </value>
            <value>
                <fullName>After work party-shared areas</fullName>
            </value>
            <value>
                <fullName>Function room birthdays 30th,40th</fullName>
            </value>
            <value>
                <fullName>Function room older age profile 50th,60th 70th, 80th</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Company overnight stays/Corporate away days</fullName>
            </value>
            <value>
                <fullName>Wedding</fullName>
            </value>
            <value>
                <fullName>Private Dining /Restaurant</fullName>
            </value>
            <value>
                <fullName>Hens and stags</fullName>
            </value>
            <value>
                <fullName>Engagement</fullName>
            </value>
            <value>
                <fullName>Venue with stage</fullName>
            </value>
            <value>
                <fullName>Quiz night</fullName>
            </value>
            <value>
                <fullName>Halloween</fullName>
            </value>
            <value>
                <fullName>PR Event</fullName>
            </value>
            <value>
                <fullName>Awards Ceremony/Company Anniversary</fullName>
            </value>
            <value>
                <fullName>Hotel with Accommodation</fullName>
            </value>
            <value>
                <fullName>Networking event</fullName>
            </value>
            <value>
                <fullName>Charity Event</fullName>
            </value>
            <value>
                <fullName>Company Quarterly Event</fullName>
            </value>
            <value>
                <fullName>Sports and Social</fullName>
            </value>
            <value>
                <fullName>Unique Venue</fullName>
            </value>
            <value>
                <fullName>21st Birthday</fullName>
            </value>
            <value>
                <fullName>Other - Tell us in description</fullName>
            </value>
            <value>
                <fullName>Small Conference</fullName>
                <isActive>false</isActive>
                <label>Small Conference</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FindaVenue/force-app/main/default/objects/Account/fields/Quality_Of_Venue_1_Highest__c.field-meta.xml
<CustomField>
    <fullName>Quality_Of_Venue_1_Highest__c</fullName>
    <label>Quality Of Venue (1 Highest)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FindaVenue/force-app/main/default/objects/Account/fields/QualityFormula__c.field-meta.xml
<CustomField>
    <fullName>QualityFormula__c</fullName>
    <formula>VALUE(TEXT(Quality_Of_Venue_1_Highest__c))</formula>
    <label>QualityFormula</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

FindaVenue/force-app/main/default/objects/Account/fields/Reception_Standing_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Reception_Standing_Capacity__c</fullName>
    <label>Reception Standing Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

FindaVenue/force-app/main/default/objects/Account/fields/Theatre_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Theatre_Capacity__c</fullName>
    <label>Theatre Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

FindaVenue/force-app/main/default/objects/Account/fields/Venue_Type_New__c.field-meta.xml
<CustomField>
    <fullName>Venue_Type_New__c</fullName>
    <label>Venue Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hotel</fullName>
            </value>
            <value>
                <fullName>Bar</fullName>
            </value>
            <value>
                <fullName>Restaurant</fullName>
            </value>
            <value>
                <fullName>Outdoor  sports day  venue</fullName>
            </value>
            <value>
                <fullName>Stadium venue</fullName>
            </value>
            <value>
                <fullName>Conference centre</fullName>
            </value>
            <value>
                <fullName>Resort</fullName>
            </value>
            <value>
                <fullName>Castle</fullName>
            </value>
            <value>
                <fullName>Landmark Venue</fullName>
            </value>
            <value>
                <fullName>Unique Venue</fullName>
            </value>
            <value>
                <fullName>Team Building Venue</fullName>
            </value>
            <value>
                <fullName>Warehouse</fullName>
            </value>
            <value>
                <fullName>Theatre</fullName>
            </value>
            <value>
                <fullName>Live Music Venue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FindaVenue/force-app/main/default/objects/Account/recordTypes/Venue.recordType-meta.xml
<RecordType>
    <fullName>Venue</fullName>
    <active>true</active>
    <label>Venue</label>
</RecordType>

FindaVenue/force-app/main/default/classes/SearchVenueInvocable.cls
public without sharing class SearchVenueInvocable {

    public class InputRequest {
        @InvocableVariable(label='Event Scenario')
        public String eventScenario;
        
        @InvocableVariable(label='Venue Type')
        public String venueType;

        @InvocableVariable(label='Event Location')
        public String eventLocation;

        @InvocableVariable(label='Quantity Min')
        public Integer quantityMin;
        
        @InvocableVariable(label='Quantity Max')
        public Integer quantityMax;
        
        @InvocableVariable(label='Capacity')
        public Integer capacity;
    }

    public class OutputResponse {
        @InvocableVariable(label='Account Record')
        public List<Account> accountRecList;

    }

    @InvocableMethod(label='Search Events Dynamically')
    public static List<OutputResponse> searchEvents(List<InputRequest> requests) {
        List<OutputResponse> results = new List<OutputResponse>();
        String fullQuery;

        for (InputRequest req : requests) {
            String query = 'SELECT Id, Name,Entire_Venue_Capacity__c,Theatre_Capacity__c,Banquet_Capacity_double__c,Reception_Standing_Capacity__c,Area__c,Quality_Of_Venue_1_Highest__c, RecordType.Name FROM Account WHERE ';
            List<String> conditions = new List<String>();
            
            if (req.quantityMin != null) {
                conditions.add('QualityFormula__c  >='+ req.quantityMin);
            }
            
            if (req.quantityMax != null) {
                conditions.add('QualityFormula__c  <='+ req.quantityMax);
            }
            
            if (req.capacity != null) {
                conditions.add('Entire_Venue_Capacity__c >='+ req.capacity);
            }
            
            if (String.isNotBlank(req.venueType)) {
                String venueType = 'Bar';
                conditions.add('Venue_Type_New__c = '+ '\'' + req.venueType + '\'');
            }
            if (String.isNotBlank(req.eventLocation)) {
                conditions.add('Area__c  = '+ '\'' + req.eventLocation + '\'');
            }
            
            System.debug('eventScenario: ' + req.eventScenario);
            if (String.isNotBlank(req.eventScenario)) {
                List<String> interests = req.eventScenario.split(';');
                    
                    // Escape any single quotes in values
                    for (Integer i = 0; i < interests.size(); i++) {
                        interests[i] = interests[i].replace('\'', '\\\'');
                    }
                
                conditions.add('Event_Scenarios__c INCLUDES (\'' + String.join(interests, '\', \'') + '\')');
            }
            
            fullQuery = query + String.join(conditions, ' AND ');
        	
        }
        
        //Check Dyanmic Query
        fullQuery = fullQuery.trim();
        
        // Check if it ends with 'WHERE'
        if (fullQuery.endsWith('WHERE')) {
            // Remove 'WHERE' and any trailing spaces
            fullQuery = fullQuery.substring(0, fullQuery.length() - 'WHERE'.length()).trim();
        }
        
        
        System.debug('Dynamic Query: ' + fullQuery);
        List<Account> venueAccount = Database.query(fullQuery);
        List<Account> potentialVenues = new List<Account>();
        
        for (Account acct : venueAccount) {
            if(acct.RecordType.Name == 'Venue'){
                potentialVenues.add(acct);
               
            }
        }
		OutputResponse res = new OutputResponse();
        res.accountRecList = potentialVenues;
        results.add(res);
        return results;
    }
}